# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  overlay_rd_type:
    documentation_options:
      filename: Network Services
      table: Global Network Services Settings
    type: dict
    description: |
      Specify RD type.
      Route Distinguisher (RD) for L2 / L3 services is set to <overlay_loopback>:<vni> per default.
      By configuring overlay_rd_type the Administrator subfield (first part of RD) can be set to other values.
      Note:
      RD is a 48-bit value which is split into <16-bit>:<32-bit> or <32-bit>:<16-bit>.
      For loopback or 32-bit ASN/number the VNI can only be a 16-bit number.
      For 16-bit ASN/number the VNI can be a 32-bit number.
    keys:
      admin_subfield:
        type: str
        convert_types:
          - int
        description: |
          "vtep_loopback" or "bgp_as" or <IPv4 Address> or interger between <0-65535> or integer between <0-4294967295> or "overlay_loopback_ip".
        default: "overlay_loopback_ip"
      admin_subfield_offset:
        type: str
        convert_types:
          - int
        description: |
          Offset can only be used if admin_subfield is an interger between <0-4294967295> or "switch_id".
          Total value of admin_subfield + admin_subfield_offset must be <= 4294967295.
