[package]
name = "passwords"
version = "0.1.0"
edition = "2021"

[dependencies]
sha-crypt = { version = "0.5.0", features = ["simple"] }
pyo3 = "0.23.3"

[lib]
# See https://github.com/PyO3/pyo3 for details
