hostname: edge3
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.42.5
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Loopback0
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 12000
    remote_as: '65000'
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      additional_paths:
        receive: true
        send:
          any: true
  neighbors:
  - ip_address: 192.168.42.1
    peer_group: WAN-OVERLAY-PEERS
    description: rr1
  - ip_address: 192.168.42.2
    peer_group: WAN-OVERLAY-PEERS
    description: rr2
  - ip_address: 192.168.42.3
    peer_group: WAN-OVERLAY-PEERS
    description: rr3
  vrfs:
  - name: SE_LAB
    router_id: 192.168.42.5
    rd: 192.168.42.5:201
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 201:201
      export:
      - address_family: evpn
        route_targets:
        - 201:201
    redistribute_routes:
    - source_protocol: connected
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: SE_LAB
  tenant: SE_LAB
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 192.168.42.5/32
ip_security:
  ike_policies:
  - name: dataPlaneIkePolicy
    local_id: 192.168.42.5
  - name: IKEAUTOVPN
    local_id: 192.168.42.5
  sa_policies:
  - name: dataPlaneSaPolicy
  - name: SAAUTOVPN
  profiles:
  - name: dataPlaneIpsecProfile
    ike_policy: dataPlaneIkePolicy
    sa_policy: dataPlaneSaPolicy
    connection: start
    shared_key: 0112140D481F07123713705
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: AUTOVPNTUNNEL
    ike_policy: IKEAUTOVPN
    sa_policy: SAAUTOVPN
    connection: start
    shared_key: 0112140D481F07
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: dataPlaneIpsecProfile
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ethernet_interfaces:
- name: Ethernet4
  peer_type: l3_interface
  ip_address: 192.168.3.1/24
  shutdown: false
  description: Client LAN Network
  type: routed
  vrf: SE_LAB
dps_interfaces:
- name: Dps1
vxlan_interface:
  Vxlan1:
    description: edge3_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback0
      vrfs:
      - name: SE_LAB
        vni: 201
